New "Content by owner" View
localgovdrupal/localgov_workflows pull request #104
Opened 2024-06-28 17:28 UTC by MariosORION

This is for issue https://github.com/localgovdrupal/localgov_workflows/issues/85.

Changes:

- Adding new View that lists content by owner (relationship to service contact required):
<img width="1471" alt="localgov_workflows_notifications-issue-85-content-by-user-view-back-office" src="https://github.com/localgovdrupal/localgov_workflows/assets/131253559/d3beb71e-ab30-484b-96fd-a59f65d23a95">

- Adding dynamic menu link that only gets placed if the View above is present:
<img width="280" alt="localgov_workflows_notifications-issue-85-dynamic-menu-link" src="https://github.com/localgovdrupal/localgov_workflows/assets/131253559/aacd5b4d-1744-4a44-ac52-d431ee37b683">

- Adding dynamic local task that only gets generated if the View above is present (see below for screenshot).

I've tested this with a new user, service contact tied to that user and a service page with that service contact assigned; here's how the new View looks like (some columns are sortable just like the vanilla content View):
<img width="1530" alt="localgov_workflows_notifications-issue-85-content-by-user-view-and-dynamic-local-task" src="https://github.com/localgovdrupal/localgov_workflows/assets/131253559/37d5b9d4-5a5d-4fcf-9e3a-a3d609aad490">

2024-07-30 09:37 UTC, markconroy commented
@MariosORION can you check the merge conflict issue here, and I can give it a test then. Thanks.

2024-07-31 09:59 UTC, MariosORION commented
@markconroy thanks for reviewing - Conflicts resolved but some tests are failing - do we resolve these on the main repo?

2024-07-31 12:09 UTC, stephen-cox commented
@MariosORION All tests are passing in the 1.x branch so it's likely that something in the PR is breaking them. Unfortunately, Paratest is not giving a nice error message so the tests will need to be run locally to find what is breaking.

If you want a hand looking at this, are you able to run the tests for this module and post error here? This should allow us to debug it.

2024-08-05 17:35 UTC, MariosORION commented
@stephen-cox I tried to set up tests to run them locally with no luck. I'll give it another go but if you have any hints on how to configure them locally with PHPStorm feel free to share...

2024-08-06 10:35 UTC, stephen-cox commented
@MariosORION Are you using Lando or DDev for development? These should both be setup to run tests out of the box.

For Lando, you can run PHPUnit tests just for this module with: `lando phpunit web/modules/contrib/localgov_workflows`

2024-09-04 14:33 UTC, stephen-cox commented
@MariosORION I have run the PHPUnit tests locally and (as I suspected) the errors are due to schema errors on the view configuration. There are a number of these errors

```
Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for views.view.localgov_content_by_owner with the following errors: views.view.localgov_content_by_owner:display.default.display_options.fields.changed.settings.time_diff.description missing schema

/app/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:98
/app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
/app/web/core/lib/Drupal/Core/Config/Config.php:230
/app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:278
/app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:486
/app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:257
/app/web/core/lib/Drupal/Core/Entity/EntityBase.php:354
/app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:614
/app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:389
/app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:149
/app/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
/app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:326
/app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
/app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:500
/app/web/core/tests/Drupal/Tests/BrowserTestBase.php:575
/app/web/core/tests/Drupal/Tests/BrowserTestBase.php:370
/app/web/modules/contrib/localgov_workflows/modules/localgov_workflows_notifications/tests/src/Functional/ServiceContactWidgetTest.php:59
/app/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
```

There's also an error coming from the kernel test as the view is in the `install` directory. As it's a view that provides extra functionality I suggest moving it into the `optional` directory.

2024-09-04 14:36 UTC, stephen-cox requested changes
I've made a couple of suggestions that should fix the failing tests.

2024-09-04 14:36 UTC, stephen-cox commented on modules/localgov_workflows_notifications/config/install/views.view.localgov_content_by_owner.yml
> +              description: ''
Deleting this line should fix one error from our tests.

2024-09-04 14:36 UTC, stephen-cox commented on modules/localgov_workflows_notifications/config/install/views.view.localgov_content_by_owner.yml
I suggest moving this in the `config/optional` directory.

2024-09-04 14:44 UTC, MariosORION commented
Thanks for reviewing @stephen-cox , I'll put in some time this afternoon to clear this up.

2024-09-04 14:53 UTC, MariosORION commented on modules/localgov_workflows_notifications/config/install/views.view.localgov_content_by_owner.yml
> +              description: ''
This is now done.

2024-09-04 14:53 UTC, MariosORION commented on modules/localgov_workflows_notifications/config/install/views.view.localgov_content_by_owner.yml
This is now done.

2024-09-04 15:27 UTC, stephen-cox commented
This now works fine. There are no filters on the view, but there's further discussion on this on the issue, but for this it comes down to whether this is required sooner rather than later. If we want this sooner we can merge this now, but when the filters are ready we will need an update hook to apply them to existing installs.

One further thought is the content tasks are now a bit busy and don't look good at medium screen widths 

![image](https://github.com/user-attachments/assets/cfba9054-412a-4dba-a1a4-ed0e9c967107)

Should the link for this be moved under the content task?

Do you have thoughts on these things @willguv?

2024-10-21 16:05 UTC, willguv commented
@stephen-cox @MariosORION I've got a slight change to this. We also need to be vary about calling these contacts "owners" as they don't own the content, just check it

So how about:

**1) Put "Content by owner" in the "Service Contacts" menu** 

- Tab 1 is labelled "Contacts"and shows the service contact view
- Tab 2 is labelled "Content" and shows the content by owner view

**2) On the "Contacts" view, provide a "View content" option in the edit menu of each contact. Links to a view of content checked by that person

2024-10-22 11:22 UTC, finnlewis commented
@MariosORION would you be able to address the changes suggested by @willguv in the last comment?

2024-10-22 13:47 UTC, MariosORION commented
I'll be working on these @finnlewis @willguv.

2024-11-01 17:31 UTC, MariosORION commented
@willguv regarding #1, how about something like that:
<img width="453" alt="Screenshot 2024-11-01 at 17 30 12" src="https://github.com/user-attachments/assets/08ae679b-cd13-45cf-af79-8a966a64bd0b">

<img width="1410" alt="Screenshot 2024-11-01 at 17 30 21" src="https://github.com/user-attachments/assets/c7d0a532-e055-4c65-9e5b-39fb0cb697bf">

<img width="1408" alt="Screenshot 2024-11-01 at 17 30 28" src="https://github.com/user-attachments/assets/2eb6c130-2f1b-4e2c-a77b-1905f0467b7a">

2024-11-05 11:25 UTC, stephen-cox reviewed
@MariosORION This looks to work well for new installs!

@willguv Do we want to add this to existing installs?

From the looks of the code we just need to add an update hook to install the view configuration

2024-11-05 11:25 UTC, stephen-cox approved these changes

2024-11-05 11:48 UTC, MariosORION commented
@stephen-cox thanks for reviewing!
(Yes, the View is the only thing that needs importing as the custom code only runs if the View is enabled).

2024-11-05 11:56 UTC, willguv commented
Lovely job @MariosORION thanks for doing this

@stephen-cox would be great to include for existing installs please

2024-11-05 12:11 UTC, willguv commented
@MariosORION could you do an update hook for this please?

2024-11-05 12:58 UTC, MariosORION commented
@willguv sure, @stephen-cox can you please give the added update hook a go?

2024-11-19 11:47 UTC, finnlewis commented
Just tested on a fresh install, and seems to be working as expected! Nice!

2024-11-19 11:47 UTC, finnlewis approved these changes

2024-11-19 11:51 UTC, finnlewis commented
Ooh... the update hook works too! So the view will be enabled by existing installations.

2024-11-19 12:16 UTC, merged

2024-11-19 12:21 UTC, finnlewis commented
@MariosORION thanks so much for this! 

One thing that would be good in future to is align commit messages with Drupal recommendations, using the imperative. For example 

"Fix coding standards. #85 " rather than "85; CS "

@ekes  mentioned that there are recommendations on Drupal.org that we will dig out.

2024-11-20 10:51 UTC, MariosORION commented
@finnlewis good shout, thanks :)